version: '3.3'
services:
  webserver:
    build: .
    ports:
      - "8089:80"
    links:
      - db:db
    restart: always
    volumes:
      - ./html:/var/www/html/
    depends_on:
      - db
                                                                                                                            
  db:
    container_name: db_sql
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=nonamed
      - MYSQL_USER=N0Named
      - MYSQL_PASSWORD=N0Named123#@!
      - MYSQL_DATABASE=sqli
    volumes:
      - ./data:/var/lib/mysql
